services:
  cart-postgres:
    image: postgres:13.22-alpine3.21
    volumes:
      - cart-postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: products_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10

  customer-postgres:
    image: postgres:13.22-alpine3.21
    volumes:
      - customer-postgres:/var/lib/postgresql/data
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: customers_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10

  sonarqube-db:
    image: postgres:latest
    container_name: ecom-postgress-sonarqube
    environment:
      POSTGRES_DB: sonar
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: s0nar
    ports:
      - 5439:5432
    volumes:
      - sonarqube_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10

  sonar:
    image: sonarqube
    container_name: ecom-sonarqube
    ports:
      - 9000:9000
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://sonarqube-db:5439/sonar
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: s0nar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    depends_on:
      sonarqube-db:
        condition: service_healthy

volumes:
  cart-postgres:
  customer-postgres:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  sonarqube_db: