spring.application.name: customer-service

spring:
  datasource:
    url: jdbc:postgresql://localhost:${CUSTOMER_SERVICE_DB_PORT:5434}/${CUSTOMER_SERVICE_DB_NAME:customers_db}
    username: ${CUSTOMER_SERVICE_DB_PASSWORD:postgres}
    password: ${CUSTOMER_SERVICE_DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update

keycloak:
  realm: ecom
  url: http://localhost:8088
  client-id: customer-service-client
  client-secret: ${KEYCLOAK_CLIENT_SECRET}

spring.security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: ${keycloak.url}/realms/${keycloak.realm}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka:eureka@localhost:8761/eureka/

server:
  port: 0
  compression:
    enabled: true

logging:
  level:
    org:
      springframework:
        security: DEBUG