spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:${PAYMENT_SERVICE_DB_PORT:5438}/${PAYMENT_SERVICE_DB_NAME:payment_db}
    username: ${PAYMENT_SERVICE_DB_PASSWORD:postgres}
    password: ${PAYMENT_SERVICE_DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update

# Configuration Stripe
stripe:
  api-key: ${STRIPE_API_KEY}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka:eureka@localhost:8761/eureka/

server:
  port: 0
  compression:
    enabled: true