spring.application.name: cart-service

spring:
  datasource:
    url: jdbc:postgresql://localhost:${CART_SERVICE_DB_PORT:5433}/${CART_SERVICE_DB_NAME:carts_db}
    username: ${CART_SERVICE_DB_PASSWORD:postgres}
    password: ${CART_SERVICE_DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka:eureka@localhost:8761/eureka/

server:
  port: 0
  compression:
    enabled: true

# TODO security config